### ISSUE TITLE
feat: Add Try-Catch Blocks to Handle Errors in `createNewConversation` Function in `Copilot.tsx`

### ISSUE THREAD

**Issue by Arindam200** [pieces-app/example-typescript#113]
## **Description:**
The `createNewConversation` function in the `Copilot.tsx` file currently lacks error handling. To improve the robustness of the code, we should add try-catch blocks to handle any potential errors that may occur during the execution of this function.

## **Proposed Change:**
Refactor the function to include try-catch blocks for error handling:
```javascript
const createNewConversation = async () => {
    try {
        // Function logic here
    } catch (error) {
        console.error("Error creating new conversation:", error);
        // Additional error handling logic if necessary
    }
};
```

## **Steps to Reproduce:**
1. Open the `Copilot.tsx` file.
2. Locate the `createNewConversation` function.
3. Refactor the function as proposed above to include try-catch blocks.

## **Expected Outcome:**
The function should handle any errors gracefully, logging them to the console and preventing the application from crashing.

## **Additional Notes:**
- Ensure that the refactored function is tested thoroughly to confirm that it handles errors correctly.
- Consider adding user-friendly error messages or notifications if appropriate.

Feel free to reach out if there are any questions or if further clarifications are needed.

**Comment by OlibhiaGhosh** [comment]
I would like to work on this issue

**Comment by Arindam200** [comment]
Go Ahead @OlibhiaGhosh
