### ISSUE TITLE
feat: Remove Unused askQuestion Function from Copilot.tsx

### ISSUE THREAD

**Issue by Arindam200** [pieces-app/example-typescript#114]
## **Description:**
The `askQuestion` function in the `Copilot.tsx` file is currently not being used anywhere in the codebase. To keep the code clean and maintainable, we should remove this unused function.

## **Steps to Reproduce:**
1. Open the `Copilot.tsx` file.
2. Locate the `askQuestion` function.
3. Remove the function from the file.

## **Expected Outcome:**
The `Copilot.tsx` file should no longer contain the unused `askQuestion` function, resulting in a cleaner and more maintainable codebase.

## **Additional Notes:**
- Ensure that the removal of this function does not affect any other parts of the application.
- Verify that there are no references to this function elsewhere in the codebase.

Feel free to reach out if there are any questions or if further clarifications are needed.

**Comment by OlibhiaGhosh** [comment]
I would like to work on this issue

Can you assign this to me?

**Comment by Arindam200** [comment]
Sure! Feel free to make a PR @OlibhiaGhosh
