### ISSUE TITLE
feat: Wrap API Calls in try/catch Blocks in Assets.tsx

### ISSUE THREAD

**Issue by Arindam200** [pieces-app/example-typescript#128]
## Description
The current implementation in `Assets.tsx` may not consistently handle errors from API calls. To improve error handling and ensure that any issues are properly caught and logged, we should wrap all API calls in `try/catch` blocks.

## Proposed Solution
Refactor the code in `Assets.tsx` to wrap all API calls in `try/catch` blocks. This will ensure that any errors are caught and can be handled appropriately, improving the robustness of the application.

## Detailed Steps

1. **Identify API Calls:**
   - Locate all instances in `Assets.tsx` where API calls are made.

2. **Wrap in try/catch:**
   - Wrap each API call in a `try/catch` block.
   - Ensure that any errors are logged or handled appropriately within the `catch` block.

3. **Testing:**
   - Ensure that the refactored code is thoroughly tested.
   - Write unit tests to verify that errors are properly caught and handled.
   - Test the application to ensure that it behaves correctly when API calls fail.

#### Benefits
- **Improved Error Handling:** Wrapping API calls in `try/catch` blocks ensures that errors are caught and handled, preventing unhandled exceptions.
- **Better Debugging:** Logging errors provides valuable information for debugging and resolving issues.
- **Robustness:** The application becomes more robust and resilient to failures in API calls.

#### Additional Notes
- **Consistency:** Ensure that all API calls throughout `Assets.tsx` are consistently wrapped in `try/catch` blocks.
- **Logging:** Consider using a logging library or service for better error tracking and monitoring.

By wrapping API calls in `try/catch` blocks in `Assets.tsx`, we can enhance the error handling capabilities of the application, making it more reliable and easier to debug.

**Comment by dhirajudhani** [comment]
Hi @Arindam200 I love to contribute this issue can you assign this to me

**Comment by Arindam200** [comment]
Go Ahead @dhirajudhani

**Comment by dhirajudhani** [comment]
hii @Arindam200 I have created a pr request please review and if there are any changes please let me know
