### ISSUE TITLE
feat: Add Prettier for Uniform Code Formatting

### ISSUE THREAD

**Issue by Arindam200** [pieces-app/example-typescript#129]
## Description
The current codebase lacks a consistent code formatting style, which can lead to readability issues and make collaboration more challenging. To address this, we should integrate Prettier, an opinionated code formatter, into the project. Prettier will automatically format the code according to a set of predefined rules, ensuring uniformity across the entire codebase.

## Proposed Solution
Integrate Prettier into the project and configure it to enforce consistent code formatting. This will involve installing Prettier, setting up configuration files, and updating the project's scripts to include Prettier checks.

## Detailed Steps

1. **Install Prettier:**
   - Add Prettier as a development dependency.
     ```bash
     npm install --save-dev prettier
     ```

2. **Create Prettier Configuration File:**
   - Create a `.prettierrc` file in the root of the project to define the formatting rules.
   
   example:
   
     ```json
     {
       "semi": true,
       "singleQuote": true,
       "trailingComma": "es5",
       "printWidth": 80,
       "tabWidth": 2
     }
     ```

3. **Update Package Scripts:**
   - Add scripts to `package.json` to format the code and check for formatting issues.
   
     ```json
     "scripts": {
       "format": "prettier --write \"src/**/*.{js,jsx,ts,tsx,json,css,scss,md}\"",
       "format:check": "prettier --check \"src/**/*.{js,jsx,ts,tsx,json,css,scss,md}\""
     }
     ```

4. **Format Existing Code:**
   - Run the Prettier format script to format the existing codebase.
     ```bash
     npm run format
     ```

5. **Documentation:**
   - Update the project documentation to include instructions on how to use Prettier and the new scripts.

## Benefits
- **Consistent Code Style:** Ensures that all code follows a uniform style, improving readability and maintainability.
- **Automated Formatting:** Reduces the need for manual code formatting, saving time and reducing errors.
- **Improved Collaboration:** Makes it easier for multiple developers to work on the same codebase without style conflicts.

## Additional Notes
- **Editor Integration:** Encourage team members to install Prettier plugins for their code editors to automatically format code on save.
- **Customization:** The Prettier configuration can be customized to fit the team's preferred coding style.

By integrating Prettier into the project, we can enforce a consistent code style across the entire codebase, making it easier to read, maintain, and collaborate on.

**Comment by shagunsharma6677** [comment]
I understand the enhancement. Can you please assign this issue to me.
Thanks

**Comment by dhirajudhani** [comment]
I have previously worked on this same type of issue , @Arindam200  can you assign me this issue 
Thanks

**Comment by Arindam200** [comment]
Hey @shagunsharma6677 , Feel Free to work on this. 

Also, @dhirajudhani you can collaborate with Shagun for this PR.
