### ISSUE TITLE
config: Add option to Change baseURL for Backend Calls in Ubuntu/Linux Environment

### ISSUE THREAD

**Issue by VishalPawar1010** [pieces-app/example-typescript#136]
### Bug Description

While developing on a Linux environment, I encountered an issue where backend calls are made to port `1000` by default, but the `Pieces OS` instance (backend server) is running on port `5323`. There is currently no option to change the `baseURL` for these backend calls, causing the development environment to malfunction.

### Steps to Reproduce

1. Set up the development environment on a Linux machine.
2. Run the Pieces OS instance (backend server) on local, which by default exposes on port 5323.
3. Run `npm start`
4. Observe that all backend API calls are made to port 1000 by default.

![Screenshot from 2024-07-18 12-26-28](https://github.com/user-attachments/assets/4fcd8501-9b04-4fcf-ac33-a05a199b866a)

### Your operating system

Linux

### Your Node version (`node -v`)

v18.x

### Your Pieces OS Version

Pieces OS Version: 10.0.1

**Comment by VishalPawar1010** [comment]
Hey @shivay-at-pieces , 
I analysed the [TypeScript SDK
](https://github.com/pieces-app/pieces-os-client-sdk-for-typescript) and got a approach to resolve this issue.
Using ` new Pieces.Configuration({
  basePath: BASE_URL,
});` and configure `BASE_URL` according to platform.

Can I please grab this issue? I have implemented & tested this on local and it works.

**Comment by shivay-at-pieces** [comment]
Sure go ahead!  thanks for bringing this up

**Comment by VishalPawar1010** [comment]
Hey @shivay-at-pieces ,
Raised the PR which resolves this issue. Could you please review and let me know for any mofifications.
Thanks
