### ISSUE TITLE
Improve animation for "You're Connected" Text

### ISSUE THREAD

**Issue by jordan-pieces** [pieces-app/example-typescript#55]
Currently this animation could just use a bit of slight improvement and maybe some upgrades when the time comes. Related to #39 that was merged recently 👍

**Comment by Arindam200** [comment]
Can I work on this?

**Comment by jordan-pieces** [comment]
@Arindam200 once the issue #37 is done then we can revisit this one here and get it assigned to you 👍

**Comment by Arindam200** [comment]
I have made the PR for #37

**Comment by jordan-pieces** [comment]
> I have made the PR for #37

Awesome should be reviewing and merging today 👍

**Comment by jordan-pieces** [comment]
@Arindam200 have you already started working on this?

**Comment by Arindam200** [comment]
Today, I'll start working on it.
