### ISSUE TITLE
Refactor Inline Styles of `App.tsx` to Global CSS

### ISSUE THREAD

**Issue by Arindam200** [pieces-app/example-typescript#77]
## Description
The current usage of inline styles in `App.tsx` is impacting code readability. It would be beneficial to refactor these inline styles and migrate them to the `global.css` file for better maintainability.

If it's approved, I want to work on this Issue.

## Steps to Reproduce
1. Open `App.tsx`.
2. Identify and review the usage of inline styles within the component.

## Expected Behavior
Inline styles in `App.tsx` should be removed, and the styling logic should be moved to the `global.css` file.

## ScreenShot: 
![image](https://github.com/pieces-app/example-ts/assets/109217591/580458aa-73b7-427e-ba6f-aa3db446a6d4)

**Comment by jordan-pieces** [comment]
@Arindam200 are you planning to complete #8 before working on this issue? if that is the case it would be awesome if you could guide @pythonistical in the meantime to get going on this if any is needed. let me know before we assign this issue 👍

**Comment by Arindam200** [comment]
Actually while working on #8, I've already made these changes locally. So I would like to create a PR for this. 

@pythonistical can take another issue.
