### ISSUE TITLE
Show Snippet Preview When Selected 

### ISSUE THREAD

**Issue by jwafu** [pieces-app/example-typescript#78]
When you select a snippet in the snippet preview, you currently cannot see the snippets content other than the title. Would love to integrate this into the card as a preview, or show the preview when it is selected. 

Using something close to this should work for trying to get a specific asset on the asset snapshot using its ID and then logging the selected files string value (as Pieces.TransferableString): 

```
new Pieces.AssetApi().assetSnapshot({ asset: '<%your snippet id%>'}).then((_asset) => {
    console.log(_asset.preview.base.reference.file.string);
  })

```

This is a good starting point and would just require actually storing the ID of the asset that you want or adding this to your asset selection pipelines in your own project. Would be great to get this added as an example to the playground.

**Comment by velu-murugesan** [comment]
How can I use this code inside my projects

**Comment by agrim0312** [comment]
hey  @jordan-pieces can I take up this task ??

**Comment by jordan-pieces** [comment]
absolutely @agrim0312 let me know if there are any questions 👍

**Comment by VishalPawar1010** [comment]
Hey, @jwafu / @shivay-at-pieces - Can I please grab this issue ?

**Comment by shivay-at-pieces** [comment]
Sure @VishalPawar1010

**Comment by VishalPawar1010** [comment]
@shivay-at-pieces I would like to suggest to remove unnecessary console logs in code base, as while development and testing it's difficult to focus on our current debugging data. Or not removed it will be good to comment them out.

**Comment by shivay-at-pieces** [comment]
Sure @VishalPawar1010 feel free to create an issue with respect to the 
Code quality
Code readability
Code optimisation
Modularity

And we can tackle all of these in separate smaller issues. We can discuss on Discord
