### ISSUE TITLE
Add Search Functionality + Components 

### ISSUE THREAD

**Issue by jordan-pieces** [pieces-app/example-typescript#8]
## Issue

Currently we are not showing any search feature set inside of the example project, and would love to add this and show more information around using this inside of this location and leveraging metadata to improve search results.

This issue is a bit more challenging since the documentation has not been released yet but would be a great candidate for someone getting familiar with the repo and wanting to dive directly into the SDK logic.

## Solution 

- [ ] Learn and understand how to properly pass parameters to the search endpoint 
- [ ] Add a text input and button to manage searching a specific string 
- [ ] show the results that come back from the search endpoint

**Comment by derajohnson** [comment]
Hi @jordan-pieces can i take up this issue?

**Comment by Sophyia7** [comment]
@jordan-pieces has this been resolved as well?

**Comment by jordan-pieces** [comment]
@derajohnson this is not using the PiecesApi endpoints that are available, are you able to reconfigure your search to reflect this change? i am adding a review on your PR #33 with details on the code for using the API :)

**Comment by derajohnson** [comment]
Thanks @jordan-pieces, looking forward to the details. I think i misunderstood the task earlier.

**Comment by jordan-pieces** [comment]
hey @derajohnson there are some examples here of the different endpoints that you can use with the `PiecesApi`. 

```

**Comment by jordan-pieces** [comment]
^^ this example will log out the name of the first asset that matches on a direct text match via search. This is a good search to start with and will give you very direct responses back based on your query. You can populate that query with a string that comes from another location as well, but let me know how it goes with this endpoint! 👍

**Comment by jordan-pieces** [comment]
@derajohnson - was wondering if there was an update here?

**Comment by derajohnson** [comment]
Hi @jordan-pieces. Sorry for not tackling this sooner, my laptop crashed. Can you reassign this issue to someone else? I'll pick up more issues as soon as it is fixed. Ty!

**Comment by jordan-pieces** [comment]
@derajohnson roger that will get this out to some other users to go after, hope all is well with your computer!

**Comment by Arindam200** [comment]
I would like to Give it a try.

**Comment by jordan-pieces** [comment]
@Arindam200 would love to get this done, and think its a great new endpoint to add for use on searching the snippets. Let me know if you need any additional info as I can put together things as you need them. 👍
