### ISSUE TITLE
Bug: Undefined `chatSelected` Variable in Copilot Chat Section

### ISSUE THREAD

**Issue by Arindam200** [pieces-app/example-typescript#84]
## Issue:
Currently, in the Copilot chat section, when no chat is selected, the variable chatSelected becomes Undefined. This leads to potential errors or unexpected behavior, particularly during the first render.

## Expected Behavior:
The chatSelected variable should show `-- no chat selected --`  when no chat is selected. 

## ScreenShot:

![image](https://github.com/pieces-app/example-typescript/assets/109217591/778a4d57-9f01-43e4-b92a-2a358a76cd18)

## Note: 
I've added one check to solve this Issue. If this issue gets approved, I would love to make a PR

### Steps to Reproduce

1. Navigate to the Copilot chat section.
2. Observe the behavior when no chat is selected.

### Your operating system

None

### Your Node version (`node -v`)

v18.x

**Comment by jordan-pieces** [comment]
@Arindam200 sounds good, i think this is a good improvement and believe that @Sophyia7 brought up an issue around the chat buttons as well. Go ahead and open up a PR for this and I can review this and #83

**Comment by Arindam200** [comment]
@jordan-pieces  I'm adding the changes to this PR #83. 

Is it okay? or should I create a separate PR?

**Comment by jordan-pieces** [comment]
@Arindam200 go ahead and add it in there, ill link this issue
