### ISSUE TITLE
Implement Login and Logout Functionality to Pieces OS 

### ISSUE THREAD

**Issue by shivay-at-pieces** [pieces-app/example-typescript#91]
### Login/Connect to the Pieces Cloud account:

Connecting and Signing in API:

Use the endpoint `osApi.signIntoOS()`

Logout: 

Use the endpoint: `osApi.signOutOfOS()`

**Comment by jordan-pieces** [comment]
@pythonistical go ahead and gets started on this one, us know if you have any questions around this endpoint 😄

**Comment by pythonistical** [comment]
In which file should I fork for coding this function? And where can I learn about pieces API?

**Comment by VishalPawar1010** [comment]
Hello @shivay-at-pieces ,

I have implemented login and logout Functionality , please checkout the test video 
here : https://www.awesomescreenshot.com/video/27665717?key=10fe1fa66bd6c3d3febe8b72935ee5f4 ,
I have raised the PR for same.
Could you  please review it.

Thanks
